### PR TITLE
Fix failing unit tests

### PR DESCRIPTION
**Pull request by Cruikshanks**
As is the nature with leaving a project dormant for awhile, some things will need updating particularly anything that relies on external API's.

A number of our tests were failing and this was purely because the VCR cassettes needed to be updated.

For others we are still investigating the issues.

WIP

### CODE REVIEW

**Comment by Cruikshanks** [comment]
If you submit the changes to delete any remaining failing feature tests @baphled I can then approve. I'm happy to accept that CI won't play ball until we have done the other stuff to update ruby and rails

**Comment by Cruikshanks** [comment]
When you are ready for me to approve, just request me as a reviewer on the PR via the GitHub UI @baphled

**Comment by baphled** [comment]
I think we'll have to get @irisfaraway to approve, as we've both had commits for these fix, I can't add you @Cruikshanks.

**Comment by Cruikshanks** [comment]
Ooh, learn something new everyday!

**Pull request merged**
